Add support to Extensions table and begin ssl module

diff --git a/modules/sqlite.mod.in b/modules/sqlite.mod.in
--- a/modules/sqlite.mod.in
+++ b/modules/sqlite.mod.in
@@ -278,6 +278,9 @@ _sqlite_check_db () {
 #   -c [sqlitedb file]        To define sqlite database file.
 #   -s [schema file]          Script to use on create sqlite database file.
 #   -q [sql query]            Query to execute on sqlite database.
+#   -t [table name]           Set table name to verify. Used only
+#                             on _sqlite_exists_table function.
+#   -f [sqlite file]          Script to execute on sqlite database.
 # RESULT
 #   Variables defined:
 #     * SQLITEDB: path of sqlite database. If not set it is used value
@@ -286,6 +289,8 @@ _sqlite_check_db () {
 #                 For dbrm schema this parameter it is not needed. (optional)
 #     * SQLITE_QUERY: variable that contains query to execute. This parameter
 #                 is mandatary only for sqlite_query function.
+#     * SQLITE_TABLE: contains table name to analize.
+#     * SQLITE_FILE: contains script file to execute on sqlite database.
 # RETURN VALUE
 #   1 on error.
 #   0 on success.
@@ -295,7 +300,7 @@ _sqlite_check_args () {
 
   # Reinitialize opt index position
   OPTIND=1
-  while getopts "c:s:q:t:" opts "$@" ; do
+  while getopts "c:s:q:t:f:" opts "$@" ; do
     case $opts in
       # sqlite_create params
       c) SQLITEDB="$OPTARG";;
@@ -305,6 +310,8 @@ _sqlite_check_args () {
       q) SQLITE_QUERY="$OPTARG";;
 
       t) SQLITE_TABLE="$OPTARG";;
+
+      f) SQLITE_FILE="$OPTARG";;
 
       *) ;;
     esac
@@ -390,7 +397,6 @@ _sqlite_create () {
   fi
 
   return 0
-
 }
 #***
 
@@ -523,5 +529,85 @@ _sqlite_exists_table () {
   fi
 }
 #***
+
+#****f* sqlite/_sqlite_compile
+# FUNCTION
+#   Compile imput file on sqlite database file.
+# TODO
+#   Check if it is correct use of error_handled function
+#   or use return 1.
+# RETURN VALUE
+#   0 on success
+#   1 on error
+# SOURCE
+_sqlite_compile () {
+
+  _sqlite_check_args "$@" || error_handled ""
+  _sqlite_check_db || error_handled ""
+
+  if [ -z "$SQLITE_FILE" ] ; then
+    error_handled "Missing file to compile."
+  else
+    if [ -e "$SQLITE_FILE" ] ; then
+      error_handled "File $SQLITE_FILE not found."
+    fi
+  fi
+
+  [[ $DEBUG && $DEBUG == true ]] && \
+    echo -en "Compiling file ${SQLITE_FILE} on database ${SQLITEDB}..."
+
+  sqlite3 "$SQLITEDB" < "$SQLITE_FILE"
+  result=$?
+  if [ $result -ne 0 ] ; then
+    echo -en "Error on compile file ${SQLITE_FILE}.\n"
+  fi
+  [[ $DEBUG && $DEBUG == true ]] && echo -en "OK\n"
+
+  return $result
+
+}
+#***
+
+
+#****f* dbm/_dbm_get_table_schema_from_file
+# FUNCTION
+#  Retrieve table schema from a .sql file and save creation script
+#  to $_sqlite_ans variable.
+# RETURN VALUE
+#   1 on error
+#   0 on success.
+# SOURCE
+_sqlite_get_tschema_from_file () {
+
+  local ans=0
+  local schemafile="$1"
+  local tname="$2"
+
+  if [ ! -f "$schemafile" ] ; then
+    error_generate "(_sqlite_get_tschema_from_file): Invalid file $schemafile." "0"
+    return 1
+  fi
+
+  if [ -z "$tname" ] ; then
+    error_generate "(_sqlite_get_tschema_from_file): Invalid table name $tname." ""
+    return 1
+  fi
+
+  local sed_pattern="/CREATE TABLE ${tname} (.*/,/);/p"
+
+  _sqlite_ans=$(cat $schemafile | sed -n "$sed_pattern")
+
+  if [ $? -ne 0 ] ; then
+    ans=1
+  fi
+
+  [[ $DEBUG && $DEBUG == true ]] && \
+    echo -en "(_sqlite_get_tschema_from_file): For table $tname in schema $schemafile found:\n$_sqlite_ans\n"
+
+  return $ans
+
+}
+#***
+
 
 # vim: syn=sh filetype=sh ts=2 sw=2
diff --git a/modules/ssl.mod.in b/modules/ssl.mod.in
--- a/modules/ssl.mod.in
+++ b/modules/ssl.mod.in
@@ -6,9 +6,9 @@
 #------------------------------------------------
 
 name="ssl"
-package_authors="Geaaru"
-package_creation_date="Mar 29, 2015"
-package_version="@PACKAGE_VERSION@"
+ssl_authors="Geaaru"
+ssl_creation_date="Mar 29, 2015"
+ssl_version="0.1.0"
 
 #****f* ssl/ssl_version
 # FUNCTION
@@ -36,6 +36,9 @@ ssl_long_help () {
    echo -en "\tlong_help               Show long help informations\n"
    echo -en "\tshow_help               Show command list.\n"
    echo -en "\tversion                 Show module version.\n"
+   echo -en "\tcreate                  Create a self installer tarball of current\n"
+   echo -en "\t                        project.\n"
+   echo -en "\tinit                    Initialize SSL extension.\n"
    echo -en "---------------------------------------------------------------------------\n"
    echo -en "===========================================================================\n"
 
@@ -57,6 +60,7 @@ ssl_show_help () {
    echo -en "\tversion                 Show module version.\n"
    echo -en "\tcreate                  Create a self installer tarball of current\n"
    echo -en "\t                        project.\n"
+   echo -en "\tinit                    Initialize SSL extension.\n"
    echo -en "---------------------------------------------------------------------------\n"
    echo -en "===========================================================================\n"
 
@@ -77,7 +81,28 @@ ssl_create () {
 
   _ssl_create_args "$@" || return $result
 
+  _ssl_create || return $result
 
+  return 0
+
+}
+#***
+
+#****f* ssl/ssl_init
+# FUNCTION
+#  Initialize current DBRM database
+#  with SSL extension table.
+# SOURCE
+ssl_init () {
+
+  _ssl_check_ext "0"
+
+  if [ $? -eq 1 ] ; then
+    _sqlite_compile -c "$DRM_DB" -f ${MODULES_DIR}/extensions-scripts/ssl_sqlite_schema.sql || \
+      error_generate "Error on initialize ssl extension."
+  else
+    out_handler_print "Ssl extensions already installed. Nothing to do."
+  fi
 
   return 0
 
@@ -97,17 +122,42 @@ _ssl_create () {
 
   local result=1
 
+  _ssl_check_ext
+
+
+  return 0
 }
 #***
 
 #****f* ssl/_ssl_check_ext
 # FUNCTION
 #   Check presence of ssl extensions table.
+# RETURN VALUE
+#  1  if extension is not present.
+#  0  if extension is present
 # SOURCE
 _ssl_check_ext () {
 
   local result=1
+  local ssl_gen_err=${1:-1}
+  local exists_tb=0
 
+  # Check if exists table SslTunnels
+  _sqlite_exists_table -c "$DRM_DB" -t "SslTunnels"
+  exists_tb=$?
+
+  if [ $exists_tb -eq 0 ] ; then
+
+    if [[ $ssl_gen_err -eq 1 || $ssl_gen_err == "1" ]] ; then
+      error_generate \
+        "Ssl extensions is not present on current DBRM db.\nExecute ssl init command and try again."
+    fi
+
+    return 1
+
+  fi
+
+  return 0
 }
 #***
 
