Complete support to profile and minor fix

diff --git a/modules/sqlite.mod.in b/modules/sqlite.mod.in
--- a/modules/sqlite.mod.in
+++ b/modules/sqlite.mod.in
@@ -27,6 +27,7 @@ sqlite_show_help () {
    echo -en "\tcreate                  Create SQLite database.\n"
    echo -en "\tremove                  Remove SQLite database.\n"
    echo -en "\tquery                   Do a query to SQLite database.\n"
+   echo -en "\tshow_autoincr_seq       Show list of autoincrement sequences values.\n"
    echo -en "===========================================================================\n"
 }
 #***
@@ -54,9 +55,86 @@ sqlite_long_help () {
    fi
    echo -en "\tremove                  Remove SQLite database.\n"
    echo -en "\tquery                   Do a query to SQLite database.\n"
+   echo -en "\tshow_autoincr_seq       Show list of autoincrement sequences values.\n"
    echo -en "---------------------------------------------------------------------------\n"
    echo -en "===========================================================================\n"
 
+}
+#***
+
+#****f* sqlite/sqlite_show_autoincr_seq
+# FUNCTION
+#   Show
+# RETURN VALUE
+#   1   error
+#   0   ok
+# SOURCE
+sqlite_show_autoincr_seq () {
+
+  local query=""
+  local table=""
+  local sequence=""
+  local counter=0
+
+  [[ $DEBUG ]] && echo -en "(sqlite_show_autoincr_seq args: $@)\n"
+
+  # Shift first two input param
+  shift 2
+
+  # TODO: use a dedicate check args function.
+  _sqlite_check_args "$@"
+
+
+  query="
+    SELECT COUNT(1) AS N_SEQUENCES
+    FROM sqlite_sequence"
+
+  _sqlite_query -c "$SQLITEDB" -q "$query" || error_handled "Unexpected error!"
+
+  if [ $_sqlite_ans -eq 0 ]; then
+    out_handler_print "No sequences available."
+  else
+
+    query="SELECT * FROM sqlite_sequence"
+
+    _sqlite_query -c "$SQLITEDB" -q "$query" || error_handled "Unexpected error!"
+
+    out_hsep=1
+    out_prepost_mode="any"
+    out_htabs_mode="tabs"
+
+    out_headers[0]="TABLE"
+    out_headers[1]="SEQUENCE ID"
+
+    out_el_pre[0]="\e[1;33m"
+    out_el_pre[1]="\e[1;34m"
+
+    out_el_post[0]="\e[m"
+
+    out_tabs[0]="20"
+    out_tabs[1]="23"
+
+    IFS=$'\n'
+    for row in $_sqlite_ans ; do
+      table=`echo $row | awk '{split($0,a,"|"); print a[1]}'`
+      sequence=`echo $row | awk '{split($0,a,"|"); print a[2]}'`
+
+      out_rows[$counter]="row"${counter}
+
+      eval "row${counter}[0]=\"${table}\""
+      eval "row${counter}[1]=\"${sequence}\""
+
+      let counter++
+    done
+    unset IFS
+
+    out_handler_print_arr
+
+  fi
+
+  out_handler_clean
+
+  return 0
 }
 #***
 
